# Generated by Django 3.1.2 on 2021-11-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('waktu', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Linen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_kerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=25)),
                ('jenis_linen', models.ManyToManyField(to='sistemLinen.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linen', models.ManyToManyField(through='sistemLinen.Detail_transaksi', to='sistemLinen.Linen')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemLinen.unit_kerja')),
            ],
        ),
        migrations.AddField(
            model_name='linen',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemLinen.status'),
        ),
        migrations.AddField(
            model_name='detail_transaksi',
            name='Linen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemLinen.linen'),
        ),
        migrations.AddField(
            model_name='detail_transaksi',
            name='Transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemLinen.transaksi'),
        ),
        migrations.AddField(
            model_name='detail_transaksi',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemLinen.unit_kerja'),
        ),
    ]
