# Generated by Django 3.1.2 on 2021-11-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemLinen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_transaksi',
            name='Unit',
        ),
    ]
