# Generated by Django 3.1.2 on 2021-11-23 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemLinen', '0004_keranjang'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='waktu_keluar',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='waktu_masuk',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
